server:
  port: 8081
spring:
  application:
    name: content
    mock-key: abcde
  datasource:
    password: mpecel_pass
    url: jdbc:postgresql://localhost:5432/content
    username: mpecel
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true